<br>
<?php if (count($articulos)): ?>
<div class="row">
    <?php foreach ($articulos as $key => $value): ?>

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail" style="height:300px">
            <?php echo Html::img($value->url_320x150) ?>
            <div class="caption">
                <h4 class="pull-right"><?php echo $value->precio ?></h4>
                <h4>
                    <?php echo Html::link("articulo/ver/".$value->nombre,ucfirst($value->nombre)) ?>
                </h4>
                <p><?php echo Util::myTruncate($value->descripcion,20) ?></p>
            </div>
            <div class="ratings">
                <p class="pull-right">15 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                </p>
            </div>
        </div>
    </div>
<?php endforeach ?>
    <?php else: ?>
    <center><h3>No se Generaron Resultados</h3></center>
<?php endif ?>
</div>



<!-- <div class="col-sm-4 col-lg-4 col-md-4">
    <h4><a href="#">Like this template?</a>
    </h4>
    <p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
    <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
</div> -->

