<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>Kumbia_ecomerce</title>
  <?php Tag::css("bootstrap/css/bootstrap.min") ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("jquery/jquery.min") ?>

  <?php echo Tag::js("bootstrap/js/bootstrap.min") ?>
</head>
<body>
  <div id='content'>
  	<?php if (Auth::is_valid()): ?>
    <?php echo Html::link("sesion/logout","Logout") ?>
  <?php endif ?>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Start Bootstrap</a> -->
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="#">About</a>
          </li>
          <li>
            <a href="#">Services</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
          <?php if (Auth::is_valid() and Auth::get("role") == "admin"): ?>
          <li>
            <?php echo Html::link("articulo/nuevo","Nuevo Articulo") ?>
          </li>
          <?php endif ?>
          <li>
            <a href="<?php echo PUBLIC_PATH."sesion/login" ?>">Login</a>
          </li>
          <?php if (Auth::is_valid()): ?>
          <li>
            <a href="<?php echo PUBLIC_PATH."sesion/logout" ?>">Logout</a>
          </li>
          <?php endif ?>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->

  </nav>
  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <br>
      <div class="col-md-3">
        <br>
        <p class="lead">Jaime Irazabal Shop</p>
        <div class="list-group">
          <?php foreach ($categorias_template as $key => $value): ?>
            <?php echo html::link("index/?buscarpor=$value->nombre",$value->nombre,'class="list-group-item"') ?>
          <?php endforeach ?>
        </div>
      </div>

      <div class="col-md-9">

        <div class="row carousel-holder">
        <br>
        <br>

          <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>

                <?php for ($i=1; $i < count($imagenes_template); $i++):?>  
                  <li data-target="#carousel-example-generic" data-slide-to="<?php echo $i ?>"></li>
                <?php  endfor; ?>
                
              </ol>
              <div class="carousel-inner">
       
                <div class="item active">
                  <?php echo Html::img($imagenes_template[0]->url_800x300,'','class="slide-image"') ?>
                </div>
                <?php for ($i=1; $i < count($imagenes_template); $i++):?>  
                <div class="item">
                  <?php echo Html::img($imagenes_template[$i]->url_800x300,'','class="slide-image"') ?>
                </div>
                <?php  endfor; ?>
                
              </div>
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>
            </div>
          </div>

        </div>

        <?php View::content(); ?>

      </div>

    </div>

  </div>
  <!-- /.container -->
  <div class="container">

    <hr>

    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; <a href="jaig.net.ve">jaig.net.ve</a> <?php echo date("Y") ?></p>
        </div>
      </div>
    </footer>

  </div>

</div>
</body>
</html>
