<br>
<?php View::content() ?>
<h3>Nueva Contacto</h3>
<?php echo Form::open() ?>
<div class="form-group">
	<label>Descripción</label>
	<?php echo Form::textarea("contacto.descripcion","class='form-control' placeholder='Descripción o Guía'") ?>
</div>
<div class="form-group">
	<label>Dirección o número</label>
	<?php echo Form::text("contacto.direccion","class='form-control' placeholder='Email, Número de teléfono, etc...'") ?>
</div>
<input type="submit" value="Agregar" class="btn btn-success">
<?php echo Form::close() ?>
<hr>
<?php echo Html::link("contacto/","Lista de Contacto") ?>